"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { useAuth } from "../../components/auth-provider";
import { insforge } from "../lib/insforge";
import {
	Sparkles,
	MessageSquare,
	Mail,
	Send,
	Calendar,
	AlertCircle,
	RefreshCw,
	Loader2,
	ArrowRight,
	ExternalLink,
	CheckCircle2,
	ListTodo,
	ChevronRight,
	FileText,
	Clock,
	Star,
	Search,
	Command,
} from "lucide-react";

interface BriefItem {
	id: string;
	source: "whatsapp" | "gmail" | "telegram" | "outlook";
	iconName: string;
	summary: string;
	timestamp: string;
}

interface PriorityItem {
	id: string;
	source: "whatsapp" | "gmail" | "telegram" | "outlook";
	title: string;
	time: string;
	description: string;
	priority: "High" | "Medium" | "Low";
}

export default function DashboardPage() {
	const { user } = useAuth();
	const router = useRouter();
	const userName = user?.profile?.name || user?.email?.split("@")[0] || "User";

	const [connectedPlatforms, setConnectedPlatforms] = useState<
		Record<string, boolean>
	>({
		whatsapp: false,
		gmail: false,
		telegram: false,
		outlook: false,
	});
	const [whatsappSimulated, setWhatsappSimulated] = useState(false);

	// Brief generation states
	const [loadingSummary, setLoadingSummary] = useState(false);
	const [summaryError, setSummaryError] = useState<string | null>(null);
	const [loadingPriority, setLoadingPriority] = useState(false);
	const [priorityError, setPriorityError] = useState<string | null>(null);

	const loadingBrief = loadingSummary || loadingPriority;

	// Dashboard data generated by Gemini
	const [importantCount, setImportantCount] = useState(0);
	const [priorityCount, setPriorityCount] = useState(0);
	const [followUpsCount, setFollowUpsCount] = useState(0);
	const [briefItems, setBriefItems] = useState<BriefItem[]>([]);
	const [priorityItems, setPriorityItems] = useState<PriorityItem[]>([]);

	// Command bar
	const [commandQuery, setCommandQuery] = useState("");

	// Time-based greeting
	const getGreeting = () => {
		const hour = new Date().getHours();
		if (hour < 12) return "Good Morning";
		if (hour < 17) return "Good Afternoon";
		return "Good Evening";
	};

	// Fetch initial integration and status info
	useEffect(() => {
		if (!user) return;

		const loadPlatformStates = async () => {
			try {
				const { data } = await insforge.database
					.from("user_integrations")
					.select("platform_id, is_connected");

				const dbStatuses: Record<string, boolean> = {
					whatsapp: false,
					gmail: false,
					telegram: false,
					outlook: false,
				};

				if (data) {
					data.forEach((row: any) => {
						dbStatuses[row.platform_id] = !!row.is_connected;
					});
				}

				try {
					const res = await fetch("/api/whatsapp/status", {
						headers: { "x-user-id": user.id },
					});
					const wsData = await res.json();
					if (wsData.status === "connected") {
						dbStatuses.whatsapp = true;
						setWhatsappSimulated(!!wsData.isSimulated);
					}
				} catch (wsErr) {
					console.error("Failed to pull WhatsApp connection status:", wsErr);
				}

				setConnectedPlatforms(dbStatuses);
			} catch (err) {
				console.error("Failed to load dashboard platform configurations:", err);
			}
		};

		loadPlatformStates();
	}, [user]);

	// Load cached brief on mount
	useEffect(() => {
		if (!user) return;

		const summaryCached = localStorage.getItem(`dashboard_summary_${user.id}`);
		if (summaryCached) {
			try {
				const parsed = JSON.parse(summaryCached);
				setImportantCount(parsed.importantCount || 0);
				setPriorityCount(parsed.priorityCount || 0);
				setFollowUpsCount(parsed.followUpsCount || 0);
				setBriefItems(parsed.brief || []);
			} catch (e) {
				console.error("Failed to parse cached summary data:", e);
			}
		}

		const priorityCached = localStorage.getItem(
			`dashboard_priority_${user.id}`,
		);
		if (priorityCached) {
			try {
				const parsed = JSON.parse(priorityCached);
				setPriorityItems(parsed.priorityItems || []);
			} catch (e) {
				console.error("Failed to parse cached priority data:", e);
			}
		}

		generateDashboardBrief(false);
	}, [user]);

	const fetchSummaryCard = async (force = false) => {
		if (!user) return;
		setLoadingSummary(true);
		setSummaryError(null);

		try {
			const res = await fetch("/api/dashboard/brief?card=summary", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
					"x-user-id": user.id,
				},
				body: JSON.stringify({ forceRefresh: force }),
			});

			if (!res.ok) {
				throw new Error("Failed to generate daily brief summary.");
			}

			const data = await res.json();
			if (data.success) {
				setImportantCount(data.importantCount || 0);
				setPriorityCount(data.priorityCount || 0);
				setFollowUpsCount(data.followUpsCount || 0);
				setBriefItems(data.brief || []);

				localStorage.setItem(
					`dashboard_summary_${user.id}`,
					JSON.stringify(data),
				);
			} else {
				throw new Error(data.error || "Failed to parse AI brief.");
			}
		} catch (err: any) {
			console.error(err);
			setSummaryError(err.message || "Error communicating with AI model.");
		} finally {
			setLoadingSummary(false);
		}
	};

	const fetchPriorityCard = async (force = false) => {
		if (!user) return;
		setLoadingPriority(true);
		setPriorityError(null);

		try {
			const res = await fetch("/api/dashboard/brief?card=priority", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
					"x-user-id": user.id,
				},
				body: JSON.stringify({ forceRefresh: force }),
			});

			if (!res.ok) {
				throw new Error("Failed to generate priority agenda.");
			}

			const data = await res.json();
			if (data.success) {
				setPriorityItems(data.priorityItems || []);

				localStorage.setItem(
					`dashboard_priority_${user.id}`,
					JSON.stringify(data),
				);
			} else {
				throw new Error(data.error || "Failed to parse priority agenda.");
			}
		} catch (err: any) {
			console.error(err);
			setPriorityError(err.message || "Error communicating with AI model.");
		} finally {
			setLoadingPriority(false);
		}
	};

	const generateDashboardBrief = (force = false) => {
		fetchSummaryCard(force);
		fetchPriorityCard(force);
	};

	// Command bar submit
	const handleCommandSubmit = (e: React.FormEvent) => {
		e.preventDefault();
		if (commandQuery.trim()) {
			router.push(
				`/dashboard/ai-agent?q=${encodeURIComponent(commandQuery.trim())}`,
			);
		}
	};

	// Brief item icon helper
	const getBriefIcon = (source: string) => {
		switch (source) {
			case "gmail":
				return <Calendar className="w-4 h-4 text-indigo-500" />;
			case "outlook":
				return <FileText className="w-4 h-4 text-blue-500" />;
			case "telegram":
				return <CheckCircle2 className="w-4 h-4 text-emerald-500" />;
			default:
				return <Clock className="w-4 h-4 text-amber-500" />;
		}
	};

	// Platform logo path helper
	const getPlatformLogo = (source: string) => {
		const logos: Record<string, string> = {
			gmail: "/gmail.svg",
			whatsapp: "/whatsapp.svg",
			telegram: "/telegram.svg",
			outlook: "/outlook.svg",
			slack: "/slack.svg",
			discord: "/discord.svg",
		};
		return logos[source] || "/default-platform.svg";
	};

	// Priority dot color
	const getPriorityDot = (priority: string) => {
		switch (priority) {
			case "High":
				return "bg-rose-500";
			case "Medium":
				return "bg-amber-500";
			default:
				return "bg-blue-500";
		}
	};

	// Connected apps data for the 2×2 grid
	const connectedAppsGrid = [
		{ id: "gmail", name: "Gmail", logo: "/gmail.svg" },
		{ id: "outlook", name: "Calendar", logo: "/outlook.svg" },
		{ id: "slack", name: "Slack", logo: "/slack.svg" },
		{ id: "whatsapp", name: "WhatsApp", logo: "/whatsapp.svg" },
	];

	return (
		<div className="space-y-6 max-w-6xl mx-auto relative pb-24 text-slate-900 dark:text-white">
			{/* ─── Greeting Section ─── */}
			<div className="flex items-start justify-between">
				<div className="space-y-1">
					<h2 className="text-2xl md:text-[28px] font-bold font-display text-slate-900 dark:text-white tracking-tight leading-tight">
						{getGreeting()}, {userName}{" "}
						<span className="inline-block animate-[wave_2s_ease-in-out_infinite] origin-bottom-right">
							👋
						</span>
					</h2>
					<p className="text-[13px] text-slate-500 dark:text-slate-200">
						Here&apos;s what&apos;s happening with your day.
					</p>
				</div>
				<button
					onClick={() => generateDashboardBrief(true)}
					disabled={loadingBrief}
					className="h-9 px-4 rounded-xl bg-white dark:bg-[#121118] border border-slate-200 dark:border-white/5 text-slate-600 dark:text-white hover:bg-slate-50 dark:hover:bg-white/10 text-xs font-semibold inline-flex items-center space-x-2 transition-all cursor-pointer shadow-sm dark:shadow-none disabled:opacity-50">
					{loadingBrief ?
						<Loader2 className="w-3.5 h-3.5 animate-spin" />
					:	<RefreshCw className="w-3.5 h-3.5" />}
					<span className="hidden sm:inline">
						{loadingBrief ? "Syncing..." : "Refresh"}
					</span>
				</button>
			</div>

			{/* ─── Row 1: Command Bar (Full-Width) ─── */}
			<form onSubmit={handleCommandSubmit} className="relative">
				<div className="flex items-center h-[52px] rounded-2xl bg-white dark:bg-[#121118] border border-slate-200 dark:border-white/5 shadow-sm dark:shadow-none px-4 gap-3 transition-all focus-within:border-indigo-400 dark:focus-within:border-indigo-500/40 focus-within:shadow-[0_0_0_3px_rgba(99,102,241,0.08)]">
					<div className="w-8 h-8 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center flex-shrink-0 shadow-sm">
						<Sparkles className="w-4 h-4 text-white" />
					</div>
					<input
						type="text"
						placeholder="Ask anything or type a command..."
						value={commandQuery}
						onChange={(e) => setCommandQuery(e.target.value)}
						className="flex-1 h-full bg-transparent text-sm text-slate-700 dark:text-white placeholder:text-slate-400 dark:placeholder:text-slate-500 outline-none font-medium"
					/>
					<div className="flex items-center space-x-2 flex-shrink-0">
						<button
							type="submit"
							className="w-8 h-8 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white hover:from-indigo-600 hover:to-purple-700 transition-all cursor-pointer shadow-sm">
							<Sparkles className="w-3.5 h-3.5" />
						</button>
						<div className="hidden sm:flex items-center space-x-1 text-[11px] text-slate-400 dark:text-slate-200 font-mono bg-slate-100 dark:bg-white/5 px-2 py-1 rounded-lg border border-slate-200 dark:border-white/5">
							<Command className="w-3 h-3" />
							<span>K</span>
						</div>
					</div>
				</div>
			</form>

			{/* ─── Row 2: Today's Brief + Stats Grid (5-Columns on Desktop) ─── */}
			<div className="grid grid-cols-1 md:grid-cols-5 gap-4">
				{/* Today's Brief (takes 2 columns) */}
				<div className="md:col-span-2 bg-white dark:bg-[#121118] border border-slate-200 dark:border-white/5 rounded-2xl shadow-sm dark:shadow-none flex flex-col h-[220px]">
					{/* Section Header */}
					<div className="flex items-center justify-between px-5 pt-4 pb-2 flex-shrink-0">
						<div className="flex items-center space-x-2.5">
							<div className="w-7 h-7 rounded-lg bg-indigo-500/10 dark:bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center">
								<FileText className="w-3.5 h-3.5 text-indigo-600 dark:text-indigo-400" />
							</div>
							<h3 className="text-sm font-bold text-slate-800 dark:text-white tracking-wide">
								Today&apos;s Brief
							</h3>
						</div>
						<button
							onClick={() => router.push("/dashboard/briefing")}
							className="text-[11px] font-semibold text-slate-400 dark:text-white hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors cursor-pointer">
							View all
						</button>
					</div>

					{/* Content */}
					<div className="flex-1 px-5 pb-4 overflow-y-auto">
						{loadingSummary && briefItems.length === 0 ?
							<div className="flex flex-col items-center justify-center py-6 space-y-2 flex-1 h-full">
								<Loader2 className="w-5 h-5 text-indigo-500 animate-spin" />
								<p className="text-xs text-slate-400 dark:text-white">
									Generating...
								</p>
							</div>
						: summaryError ?
							<div className="flex flex-col items-center justify-center py-4 text-center space-y-2 text-rose-500 h-full">
								<AlertCircle className="w-5 h-5" />
								<p className="text-xs font-semibold">{summaryError}</p>
								<button
									onClick={() => generateDashboardBrief(false)}
									className="text-xs underline text-indigo-500 hover:text-indigo-600 font-medium cursor-pointer">
									Try again
								</button>
							</div>
						: briefItems.length === 0 ?
							<div className="text-center py-6 text-slate-500 dark:text-white flex flex-col items-center justify-center h-full">
								<p className="text-xs">No briefings generated yet.</p>
								<button
									onClick={() => generateDashboardBrief(false)}
									className="mt-1 text-xs font-semibold text-indigo-600 dark:text-indigo-400 hover:underline cursor-pointer">
									Sync Channels Now
								</button>
							</div>
						:	<div className="relative">
								{loadingSummary && (
									<div className="absolute inset-0 bg-white/60 dark:bg-slate-950/40 backdrop-blur-[1px] flex items-center justify-center rounded-xl z-20">
										<Loader2 className="w-5 h-5 text-indigo-500 animate-spin" />
									</div>
								)}
								<div className="space-y-1">
									{briefItems.map((item) => (
										<div
											key={item.id}
											className="flex items-start gap-3 py-2 border-b border-slate-100 dark:border-white/5 last:border-b-0 group">
											<div className="mt-1.5 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-indigo-500 dark:bg-indigo-400" />
											<div className="flex-1 min-w-0">
												<p className="text-[13px] font-medium text-slate-700 dark:text-white leading-snug line-clamp-2">
													{item.summary}
												</p>
												<p className="text-[11px] text-slate-400 dark:text-slate-205 mt-1">
													{item.timestamp}
												</p>
											</div>
											<div className="flex-shrink-0 w-7 h-7 rounded-lg bg-slate-50 dark:bg-white/5 border border-slate-100 dark:border-white/5 flex items-center justify-center">
												{getBriefIcon(item.source)}
											</div>
										</div>
									))}
								</div>
							</div>
						}
					</div>
				</div>

				{/* Important Stat Card (takes 1 column) */}
				<div
					className="md:col-span-1 group flex flex-col justify-between p-5 rounded-2xl bg-white dark:bg-[#121118] border border-slate-200 dark:border-white/5 shadow-sm dark:shadow-none hover:shadow-md dark:hover:border-white/10 transition-all cursor-pointer h-[220px]"
					onClick={() => router.push("/dashboard/briefing")}>
					<div className="flex justify-between items-start">
						<div className="w-11 h-11 rounded-2xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center shadow-sm shadow-amber-500/20">
							<AlertCircle className="w-5 h-5 text-white" />
						</div>
						<ChevronRight className="w-4 h-4 text-slate-350 dark:text-slate-500 group-hover:text-slate-500 dark:group-hover:text-slate-400 transition-colors" />
					</div>
					<div className="space-y-1">
						<p className="text-[11px] font-semibold text-slate-500 dark:text-white uppercase tracking-wider">
							Important
						</p>
						<div className="flex items-baseline space-x-2">
							<span className="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
								{importantCount}
							</span>
						</div>
						<p className="text-[11px] text-slate-450 dark:text-white">
							{importantCount > 0 ?
								`${importantCount} high priority`
							:	"All clear"}
						</p>
					</div>
				</div>

				{/* Schedule Stat Card (takes 1 column) */}
				<div
					className="md:col-span-1 group flex flex-col justify-between p-5 rounded-2xl bg-white dark:bg-[#121118] border border-slate-200 dark:border-white/5 shadow-sm dark:shadow-none hover:shadow-md dark:hover:border-white/10 transition-all cursor-pointer h-[220px]"
					onClick={() => router.push("/dashboard/briefing")}>
					<div className="flex justify-between items-start">
						<div className="w-11 h-11 rounded-2xl bg-gradient-to-br from-indigo-400 to-purple-600 flex items-center justify-center shadow-sm shadow-indigo-500/20">
							<Calendar className="w-5 h-5 text-white" />
						</div>
						<ChevronRight className="w-4 h-4 text-slate-300 dark:text-slate-500 group-hover:text-slate-500 dark:group-hover:text-slate-400 transition-colors" />
					</div>
					<div className="space-y-1">
						<p className="text-[11px] font-semibold text-slate-500 dark:text-white uppercase tracking-wider">
							Schedule
						</p>
						<div className="flex items-baseline space-x-2">
							<span className="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
								{priorityCount}
							</span>
						</div>
						<p className="text-[11px] text-slate-450 dark:text-white">
							{priorityCount > 0 ?
								`${priorityCount} event${priorityCount !== 1 ? "s" : ""} today`
							:	"No events"}
						</p>
					</div>
				</div>

				{/* Follow-Ups Stat Card (takes 1 column) */}
				<div
					className="md:col-span-1 group flex flex-col justify-between p-5 rounded-2xl bg-white dark:bg-[#121118] border border-slate-200 dark:border-white/5 shadow-sm dark:shadow-none hover:shadow-md dark:hover:border-white/10 transition-all cursor-pointer h-[220px]"
					onClick={() => router.push("/dashboard/briefing")}>
					<div className="flex justify-between items-start">
						<div className="w-11 h-11 rounded-2xl bg-gradient-to-br from-emerald-400 to-teal-600 flex items-center justify-center shadow-sm shadow-emerald-500/20">
							<CheckCircle2 className="w-5 h-5 text-white" />
						</div>
						<ChevronRight className="w-4 h-4 text-slate-300 dark:text-slate-500 group-hover:text-slate-500 dark:group-hover:text-slate-400 transition-colors" />
					</div>
					<div className="space-y-1">
						<p className="text-[11px] font-semibold text-slate-500 dark:text-white uppercase tracking-wider">
							Follow-Ups
						</p>
						<div className="flex items-baseline space-x-2">
							<span className="text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
								{followUpsCount}
							</span>
						</div>
						<p className="text-[11px] text-slate-450 dark:text-white">
							{followUpsCount > 0 ?
								`${followUpsCount} due today`
							:	"None pending"}
						</p>
					</div>
				</div>
			</div>

			{/* ─── Row 3: Large Full-Width Container Card (Connected Apps + Priority Items) ─── */}
			<div className="bg-white dark:bg-[#121118] border border-slate-200 dark:border-white/5 rounded-2xl shadow-sm dark:shadow-none p-6">
				<div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
					{/* Left Column: Connected Apps */}
					<div className="flex flex-col space-y-4">
						<div className="flex items-center justify-between">
							<div className="flex items-center space-x-2.5">
								<div className="w-7 h-7 rounded-lg bg-emerald-500/10 dark:bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
									<CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
								</div>
								<h3 className="text-sm font-bold text-slate-800 dark:text-white tracking-wide">
									Connected Apps
								</h3>
							</div>
							<button
								onClick={() => router.push("/dashboard/integrations")}
								className="text-[11px] font-semibold text-slate-400 dark:text-white hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors cursor-pointer">
								Manage
							</button>
						</div>

						<div className="grid grid-cols-2 gap-4">
							{connectedAppsGrid.map((app) => {
								const isConnected = connectedPlatforms[app.id] ?? false;
								return (
									<div
										key={app.id}
										onClick={() => router.push("/dashboard/integrations")}
										className="flex flex-col items-center justify-center py-5 px-3 rounded-xl bg-slate-50/80 dark:bg-white/[0.02] border border-slate-100 dark:border-white/5 hover:border-slate-200 dark:hover:border-white/10 hover:shadow-sm transition-all cursor-pointer group">
										<div className="w-11 h-11 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-white/10 flex items-center justify-center p-2 shadow-sm dark:shadow-none group-hover:scale-105 transition-transform">
											<Image
												src={app.logo}
												alt={app.name}
												width={26}
												height={26}
												className="object-contain"
											/>
										</div>
										<span className="text-[13px] font-semibold text-slate-700 dark:text-white mt-2.5 text-center">
											{app.name}
										</span>
										<span
											className={`text-[10px] font-semibold mt-0.5 ${isConnected ? "text-emerald-500" : "text-slate-400 dark:text-white"}`}>
											{isConnected ? "Connected" : "Not connected"}
										</span>
									</div>
								);
							})}
						</div>
					</div>

					{/* Right Column: Priority Items */}
					<div className="flex flex-col space-y-4">
						<div className="flex items-center justify-between">
							<div className="flex items-center space-x-2.5">
								<div className="w-7 h-7 rounded-lg bg-amber-500/10 dark:bg-amber-500/10 border border-amber-500/20 flex items-center justify-center">
									<Star className="w-3.5 h-3.5 text-amber-500 dark:text-amber-400" />
								</div>
								<h3 className="text-sm font-bold text-slate-800 dark:text-white tracking-wide">
									Priority Items
								</h3>
							</div>
							<button
								onClick={() => router.push("/dashboard/briefing")}
								className="text-[11px] font-semibold text-slate-400 dark:text-white hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors cursor-pointer">
								View all
							</button>
						</div>

						<div className="flex-1">
							{loadingPriority && priorityItems.length === 0 ?
								<div className="flex flex-col items-center justify-center py-12 space-y-3 h-full">
									<Loader2 className="w-5 h-5 text-indigo-500 animate-spin" />
									<p className="text-xs text-slate-400 dark:text-white">
										Loading priority items...
									</p>
								</div>
							: priorityError ?
								<div className="flex flex-col items-center justify-center py-8 text-center space-y-2 text-rose-500 h-full">
									<AlertCircle className="w-6 h-6" />
									<p className="text-xs font-semibold">{priorityError}</p>
									<button
										onClick={() => generateDashboardBrief(false)}
										className="text-xs underline text-indigo-500 hover:text-indigo-600 font-medium cursor-pointer">
										Try again
									</button>
								</div>
							: priorityItems.length === 0 ?
								<div className="text-center py-12 text-slate-500 dark:text-white flex flex-col items-center justify-center h-full">
									<p className="text-xs">No priority items detected.</p>
								</div>
							:	<div className="relative">
									{loadingPriority && (
										<div className="absolute inset-0 bg-white/60 dark:bg-slate-950/40 backdrop-blur-[1px] flex items-center justify-center rounded-xl z-20">
											<Loader2 className="w-5 h-5 text-indigo-500 animate-spin" />
										</div>
									)}
									<div className="space-y-1">
										{priorityItems.map((item) => (
											<div
												key={item.id}
												className="flex items-center gap-3 py-3 border-b border-slate-100 dark:border-white/5 last:border-b-0 group">
												{/* Platform logo */}
												<div className="w-9 h-9 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-white/10 flex items-center justify-center p-1.5 flex-shrink-0 shadow-sm dark:shadow-none">
													<Image
														src={getPlatformLogo(item.source)}
														alt={item.source}
														width={20}
														height={20}
														className="object-contain"
													/>
												</div>

												{/* Text */}
												<div className="flex-1 min-w-0">
													<p className="text-[13px] font-semibold text-slate-700 dark:text-white truncate">
														{item.title}
													</p>
													<p className="text-[11px] text-slate-400 dark:text-white capitalize">
														{item.source}
													</p>
												</div>

												{/* Time & Priority Dot */}
												<div className="flex items-center space-x-2 flex-shrink-0">
													<span className="text-[11px] text-slate-400 dark:text-white font-medium">
														{item.time}
													</span>
													<span
														className={`w-2 h-2 rounded-full ${getPriorityDot(item.priority)}`}
														title={item.priority}
													/>
												</div>
											</div>
										))}
									</div>
								</div>
							}
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
